language: python

python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4

install:
  - pip install numpy
  - pip install tqdm
  - pip install coveralls

script:
  - coverage run --source=swc2vtk setup.py test

after_success:
  - coveralls

notifications:
  slack: microbrain:dHXYnMz4KBlHXHLs64ju5h5Y
